web:
    build: app
    command: sh -c 'cd app && gunicorn --workers=3 --bind 0.0.0.0:8000 myproject.wsgi:application'
    volumes:
        - .:/dockyard
    links:
        - db
    expose:
        - "8000"

db:
    image: postgres

nginx:
    build: nginx
    ports:
        - "80:80"
    links:
        - web
